"""empty message

Revision ID: 04127ba668bd
Revises: 946d7f7e721b
Create Date: 2019-01-02 14:45:13.961241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04127ba668bd'
down_revision = '946d7f7e721b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('histories', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('histories', 'date_created')
    op.drop_column('decisions', 'date_created')
    # ### end Alembic commands ###
