"""empty message

Revision ID: 411a73e75949
Revises: 6726eeed74c9
Create Date: 2019-01-02 11:38:27.724882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411a73e75949'
down_revision = '6726eeed74c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('options', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('histories')
    # ### end Alembic commands ###
