"""empty message

Revision ID: 9258d8127a4f
Revises: 411a73e75949
Create Date: 2019-01-02 11:43:31.560959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9258d8127a4f'
down_revision = '411a73e75949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'histories', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'histories', type_='foreignkey')
    op.drop_column('histories', 'account_id')
    # ### end Alembic commands ###
